preset: recommended

risky: false
linting: true

disabled:
  - cast_spaces
  - heredoc_to_nowdoc
  - no_alias_functions
  - no_tab_indentation
  - phpdoc_var_without_name
  - single_import_per_statement
  - single_line_after_imports
  - unalign_equals
  - unary_operator_spaces
  - phpdoc_summary
  # The following were desired but causing too many
  # in-accurate reports, since they assume spaces
  # and not tabs for indentation.
  - phpdoc_indent
  - braces

enabled:
  - align_equals
  - combine_consecutive_unsets
  - no_empty_comment
  - no_useless_else
  - not_operator_with_successor_space
  - phpdoc_no_empty_return
  - phpdoc_property
