language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

global:
  - CI=true
  - CI_ENVIRONMENT=testing

# Recommended by Travis support
sudo: required
dist: precise

env:
  - DB=mysqli
  - DB=postgres
  - DB=sqlite

services:
  - memcached
  - mysql
  - postgresql
  - redis-server

script:
  - php vendor/bin/phpunit -v

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test';" -uroot
  - psql -c 'CREATE DATABASE test;' -U postgres

before_script:
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $TRAVIS_PHP_VERSION =~ ^nightly ]]; then wget https://github.com/phpredis/phpredis/archive/4.1.1.tar.gz && tar xfz 4.1.1.tar.gz && rm -r 4.1.1.tar.gz && cd phpredis-4.1.1 && phpize && ./configure && make && make install && echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi
  - composer install --prefer-source

after_success:
  - travis_retry php tests/bin/php-coveralls.phar -v
