language: php

php:
  - 7
  - 7.1

global:
  - CI=true
  - CI_ENVIRONMENT=testing

# Recommended by Travis support
sudo: required
dist: precise

env:
  - DB=mysqli
  - DB=postgres

services:
  - mysql
  - postgresql

script:
  - php vendor/bin/phpunit -v

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test';" -uroot
  - psql -c 'CREATE DATABASE test;' -U postgres

before_script:
  - composer install --prefer-source

after_success:
  - travis_retry php tests/bin/coveralls.phar
