language: php

matrix:
  include:
    - php: 7.2
      env:
        - IGNORE_PLATFORMS=false
        - DB=mysqli
    - php: 7.2
      env:
        - IGNORE_PLATFORMS=false
        - DB=postgres
    - php: 7.2
      env:
        - IGNORE_PLATFORMS=false
        - DB=sqlite
    - php: 7.3
      env:
        - IGNORE_PLATFORMS=false
        - DB=mysqli
    - php: 7.3
      env:
        - IGNORE_PLATFORMS=false
        - DB=postgres
    - php: 7.3
      env:
        - IGNORE_PLATFORMS=false
        - DB=sqlite
    - php: 7.4snapshot
      env:
        - IGNORE_PLATFORMS=true
        - DB=mysqli
    - php: 7.4snapshot
      env:
        - IGNORE_PLATFORMS=true
        - DB=postgres
    - php: 7.4snapshot
      env:
        - IGNORE_PLATFORMS=true
        - DB=sqlite
    - php: nightly
      env:
        - IGNORE_PLATFORMS=true
        - DB=postgres
    - php: nightly
      env:
        - IGNORE_PLATFORMS=true
        - DB=mysqli
    - php: nightly
      env:
        - IGNORE_PLATFORMS=true
        - DB=sqlite
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

global:
  - CI=true
  - CI_ENVIRONMENT=testing

# Recommended by Travis support
sudo: required
dist: trusty
group: edge

services:
  - memcached
  - mysql
  - postgresql
  - redis-server

script:
  - php vendor/bin/phpunit -v

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test';" -uroot
  - psql -c 'CREATE DATABASE test;' -U postgres

before_script:
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ "$IGNORE_PLATFORMS" == "true" ]; then composer install --prefer-source --ignore-platform-reqs; fi
  - if [ "$IGNORE_PLATFORMS" == "false" ]; then composer install --prefer-source; fi

after_success:
  - travis_retry php tests/bin/php-coveralls.phar -v
