language: php

php:
  - 7
  - 7.1

global:
  - CI=true
  - CI_ENVIRONMENT=testing

# Recommended by Travis support
sudo: required
dist: precise

env:
  - DB=mysqli
  - DB=postgres

services:
  - memcached
  - mysql
  - postgresql
  - redis-server

script:
  - php vendor/bin/phpunit -v

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test';" -uroot
  - psql -c 'CREATE DATABASE test;' -U postgres
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout 1.0.10
  - ./autogen.sh
  - ./configure && make check
  - make
  - sudo make install
  - cd ..
  - pecl install libsodium
  - echo "extension = libsodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-source

after_success:
  - travis_retry php tests/bin/coveralls.phar
