# When a PR is opened or a push is made, perform
# a static analysis check on the code using PHPStan.
name: PHPStan

on:
  pull_request:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**'
      - 'system/**'
      - '.github/workflows/test-phpstan.yml'
  push:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**'
      - 'system/**'

jobs:
  build:
    name: Analyze code (PHPStan)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse --level=5 app system
