# When a PR is opened or a push is made, perform
# a static analysis check on the code using Rector.
name: Rector

on:
  pull_request:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**'
      - 'system/**'
  push:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**'
      - 'system/**'

jobs:
  build:
    name: Analyze code (Rector)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl

      - name: Use latest Composer
        run: composer self-update

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --ansi --no-progress --no-suggest --no-interaction

      - name: Run static analysis
        run: vendor/bin/rector process --dry-run
